### ISSUE TITLE
Auto collect schemas recursively from usages

### ISSUE THREAD

**Issue by juhaku** [juhaku/utoipa#1065]
### Description

Currently all schemas need to be manually listed to the `OpenApi` via `#[openapi(components(schemas(...)))]` or manually by adding them directly to the `OpenApi`. While this is fine, it gets burdensome for large projects and is prone to errors and in reality is not feasible in long run.

### Solution

Allow `utoipa` to automatically collect schemas recursively within types that implement `ToSchema` trait (by derive) and all usages e.g. when type implementing `ToSchema` is defined as a request body or response body.

This does not change the fact that still handlers need to manually added to the schema either via `#[openapi(paths(...))]` or by other means.

### Tasks

- [x] Refactor request body parsing
- [x] Implement support for recursively generating schema references for types implementing `ToSchema` trait (via derive).
- [x] Implement support for recognizing recursive schemas from request body usage e.g. via `#[utoipa::path(request_body = ...)]` or from handler function argument for frameworks that supports request body auto recognition. These are `actix_web` `axum` and maybe `rocket`
- [x] Refactor response body parsing, and unify it with the request body parsing.
- [x] Implement support for recognizing recursive schemas from responses (tuples) ~maybe `IntoResponses` and `ToResponse` as well?~
- [x] Implement automatic recursive schema addition to `utoipa-axum` (request_body and responses).

Closes #1025 Closes #465

Fixes #692

Relates #662 #591 #965 #779

**Comment by leebenson** [comment]
This is an incredible addition, thanks for your hard work 👍🏻 

Migrating from Poem to Axum, the single biggest issue is runtime mismatch of schema types and _actual_ types used in practice. It's easy to return a `Json<ThingA>` in Axum and forget to update the relevant `utoipa::path` responses definition to match

To that end, Is the plan to incorporate full type inference -- e.g. path/params, return types, etc from usage? Or would it still be necessary after this round to manually decorate utoipa::path with `params()`, `body = <ReturnType>`, etc?

Either way -- this is a great step forward, thank you.

**Comment by juhaku** [comment]
> Migrating from Poem to Axum, the single biggest issue is runtime mismatch of schema types and actual types used in practice. It's easy to return a Json<ThingA> in Axum and forget to update the relevant utoipa::path responses definition to match

That's true, it has been an issue for too long, though with the 5.0.0 it will recognize the types and if something does not exist, it will fail with compile error. Moreover if you happen to rename a type, it will get renamed in `#[utoipa::path(...)]` responses as well (same goes for request bodies as they are not linked with correct spans).

> To that end, Is the plan to incorporate full type inference -- e.g. path/params, return types, etc from usage? Or would it still be necessary after this round to manually decorate utoipa::path with params(), body = <ReturnType>, etc?

Yes, this round does not yet infer response body from return types. There has actually been a hidden feature flag `auto_into_responses` which should do something like that, but that is highly experimental and is for change in future. Adding such support with certain precepts is quite straight forward e.g. It will recognize `Json<T>`  return type to `200` `application/json` of `T` and `Result<T, E>`, `200` of `T` and `500` of `E`. But since in rust it is also possible with many frameworks directly return an `impl Trait` for such cases the auto inference would not work. 

This is something that most likely will be added after the 5.0.0 release. I will see further down the road when such feature will be added nonetheless. 

For what comes to the `params` inference. For `axum` and `actix-web` that actually is possible, though not planned as of yet. Nevertheless the requirement for that is that the params will be always either wrapped with `Path<T>` or `Query<T>` in order to recognize the type of the parameters. Headers would be still necessary to list in `params(...)`

**Comment by leebenson** [comment]
Love it, thanks @juhaku!

**Comment by juhaku** [comment]
Closing as done, the `ToResponse` and `IntoResponses` will be followed in separate issue #1094

**Comment by izelnakri** [comment]
Hi @juhaku ,

I hope you dont mind I reach out to you here & on a closed issue that is only somewhat related to what I'm going to ask 😅 

I found your library to be the best possible abstract representation/declaration of a possible documentation of openapi in rust & I've seen many solutions and libraries over more than a decade, so thank you for coming up with this API, implementation and ongoing maintenance.  

> This does not change the fact that still handlers need to manually added to the schema either via #[openapi(paths(...))] or by other means.

The way I see it I think the future of http servers should be self-documenting, since most libraries don't provide optional annotations and autogenerations from its existing types, an abstract tree of openapi like what `utoipa` currently provides is very useful. Next step is `utopia` allowing these existing frameworks to convert their api's internally to utoipa internal openapi representation.

I think the next step is to accomplish this through framework bindings like `utoipa-axum` actix etc: these utoipa packages should **autogenerate** openapi documentations without *requiring any annotation* as possible, eventually piece by piece since its quite a bit of work but a general purpose solution seems possible. I suspect that you've already tried this.  I see a value in the current implementation of "having one route specific annotations above the route handler", as much as in the poem-like framework code auto-generation(code takes should precendence over the annotations above) . Thus in future developers should be able to extend the newly auto-generated openapi abstract tree with `utoipa` and optionally add additional annotations at one place(the current existing api).

In other words I think `utoipa` should provide the DX of `poem` while offering more flexibility than what `poem` provides by allowing annotations on top before code as well(current implementation). Potentially allowing poem and utoipa to even coexist together.

Have you thought about or experimented allowing auto-generation for `axum`, `actix-web` etc, until maybe even to `poem`? If an API like this would have existed, I probably could convert my `poem` dependency to `axum` and have the ultimate flexibility.  I've checked the current bindings and they are not doing much auto-generation, rather makes existing `utoipa` annotations more clear. I hope I've been clear in expression the issue/vision I have, feel free to reach out to me on discord or Telegram if you'd like me to elaborate further & thanks for your attention 😅
