### ISSUE TITLE
Refactor CI, remove deprecated usages

### ISSUE THREAD

**Issue by juhaku** [juhaku/utoipa#449]
Currently CI pipeline uses some deprecated functionalities what will be faced out by Github eventually this year. More about it here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Tasks:**

- [x] Remove deprecated usages and replace them with new alternatives.
- [ ] Update CI add clippy and format check
- [ ] Migrate to Node.js V16 Actions - Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
