### ISSUE TITLE
Automatic type recognition for path operation handlers

### ISSUE THREAD

**Issue by juhaku** [juhaku/utoipa#591]
## Description

To streamline further the `utoipa` library and to provide deeper integeration for frameworks like `actix_web`, `axum`, and `rocket` it would be great to be able to automatically recognize necessary types from operation handler and add them to the path schema of OpenAPI doc generated with `utoipa`. This will provide more automation and saves the keystrokes the user is ought to take to define `#[utoipa::path(...)]` macro content manually.

For example, from following handler function we would need to be able to recognize _`path`_, _`query`_, _`body`_ and _`response`_. These recognized values, if successful, should be added automatically to the generated OpenAPI spec.
```rust
#[utoipa::path]
async fn post_item(path: Path<PathParams>, query: Query<QueryParams>, item: Json<ItemBody>) -> Response {
    Response::Success(Item { value: "super".to_string() })
}
```

This functionality will enforce users to be more strict on what is being returned from the handler functions and what are the args given to the handler functions. Benefit of this is the users are able to declare the OpenAPI spec mostly via code and get compile errors directly to the code of invalid spec.

## Tasks

- [ ] Implement general response body recognition - All responses need to implement `IntoResponses` trait.
- [ ] Implement response body recognition for actix_web
- [ ] Implement response body recognition for axum
- [ ] Implement response body recognition for rocket
- [ ] Implement request body recognition for actix_web
- [ ] Implement request body recognition for axum
- [ ] Implement request body recognition for rocket
- [ ] Enhance current path and query parameter support in actix_web to support auto recognition
- [ ] Enhance current path and query parameter support in axum to support auto recognition
- [ ] Enhance current path and query parameter support in rocket to support auto recognition

**Comment by TheDan64** [comment]
I think related; it was really surprising (in axum) that `Path<(X, Y)>` would auto generate the path params but `Path<X>` does not

**Comment by juhaku** [comment]
Yeah, I can take a look at this at the same time.

**Comment by juhaku** [comment]
Any ideas are welcome to this one https://github.com/juhaku/utoipa/pull/649. Currently not sure at the moment how to proceed with the implementation. The biggest issue is that if I have a handler such as seen below, I can only resolve responses for `Result` type based on assumtions without the possibility to realiably change / override or ignore them later on. This practically becomes quite limiting if we assume that the responses from the given handler were only `200` for success and `default` for any possible error. Sure we can add more responses with the `responses(...)` attribute in `utoipa::path` macro, but we cannot map them reliably with the auto-resolved ones. 
```rust
#[utoipa::path]
#[get("/item")]
async fn get_item() -> Result<Json<Item<'static>>, Error> {
    Ok(Json(Item { value: "super" }))
}
```

**Comment by juhaku** [comment]
> I think related; it was really surprising (in axum) that `Path<(X, Y)>` would auto generate the path params but `Path<X>` does not

@TheDan64 This PR #668 should fix the issue in the path parameters.

**Comment by TheDan64** [comment]
@juhaku thanks! is this in 3.4.3? I seem to be having the same issue still

**Comment by juhaku** [comment]
> @juhaku thanks! is this in 3.4.3? I seem to be having the same issue still

At the moment the path parameter can be recognized according to tests in this commit: https://github.com/juhaku/utoipa/commit/7cc90b142f4404144d36effd38afd09a60c86a85.

It is not fully automatic because as the original behavior was reverted because it caused unwanted issues for many users. There is some work to do for make this implementation better but for what comes to the axum path parameters the name of the handler argument must match to the path arguments otherwise they will not be added. 
```rust
    // `id` must match to the path argument name.
    async fn get_item(id: Path<u32>) {}
    
    // `id and `id2` must match to the path argument name.
    async fn get_item(Path((id, id2)): Path<(u32, u32)>) {}
```

**Comment by snaggen** [comment]
Hi! I'm considering moving a project over to utoipa, but noticed some gaps in the type recognition for actix-web, so I put together a small patch series to close some of them (a few also cover axum and rocket). Since the patches are AI-assisted, I have kept them as independent and minimal as possible, to make them easy to review and to keep the code quality up:

- #1603 Re-enable the commented-out actix `auto_into_responses` `Result` test.
- #1604 Fix a proc macro panic for generic `Path<T>` types such as `Path<HashMap<..>>`.
- #1605 Recognize `#[actix_web::get(...)]` and other qualified route macros.
- #1606 Merge methods of `#[routes]` sharing the same path.
- #1607 Derive the request body content type from the extractor.
- #1608 Fix `Bytes` request bodies failing to compile.
- #1609 Don't require `IntoResponses` for every return type with `auto_into_responses`.
- #1610 Restore `IntoParams` recognition for `Query<T>`/`Path<T>` (#675, #677).
- #1611 Fix a rocket panic for `Data`/`TempFile` data guards.
- #1612 Support rocket `Form<Contextual<T>>`, `Strict` and `Lenient` bodies.
- #1613 Recognize `String` request bodies.
- #1614 Register schemas referenced by `IntoResponses` responses.
- #1615 Document `Json<T>` return types as `200` responses (stacked on #1609).
- #1616 Proposal: status code return types like `Created<Json<T>>` (stacked on #1614).

Most are independent; the dependencies and conflicts are noted in each PR. Feedback on #1615 and #1616 in particular is welcome, as they relate to #649.
